export default {
    USER_LOG_IN: "USER_LOG_IN",
    USER_LOG_OUT: "USER_LOG_OUT",
    USER_LOG_IN_ERROR: "USER_AUTHENTICATION_ERROR",
    USER_LOG_IN_CONFIRMED: "USER_LOG_IN_CONFIRMED",
    USER_LOG_OUT_CONFIRMED: "USER_LOG_OUT_CONFIRMED",
    USER_SIGN_UP: "USER_SIGN_UP",
    USER_SIGN_UP_ERROR: "USER_SIGN_UP_ERROR",
    USER_SIGN_UP_CONFIRMED: "USER_SIGN_UP_CONFIRMED",
    USER_CHECK_SESSION: "USER_CHECK_SESSION",

    USER_GET_SCRIPTS: "USER_GET_SCRIPTS",
    USER_GET_SCRIPTS_ERROR: "USER_GET_SCRIPTS_ERROR",

    USER_SET_SCRIPTS: "USER_SET_SCRIPTS",

    USER_SELECT_SCRIPT: "USER_SELECT_SCRIPT",
    USER_SELECT_SCRIPT_UPDATED: "USER_SELECT_SCRIPT_UPDATED",

    SCRIPT_CREATE: "SCRIPT_CREATE",
    SCRIPT_CREATE_CONFIRMED: "SCRIPT_CREATE_CONFIRMED",
    SCRIPT_CREATE_ERROR: "SCRIPT_CREATE_ERROR",
    SCRIPT_CREATE_RESET_PARAMETERS: "SCRIPT_CREATE_RESET_PARAMETERS",

    SCRIPT_UPDATE: "SCRIPT_UPDATE",
    SCRIPT_UPDATE_CONFIRMED: "SCRIPT_UPDATE_CONFIRMED",
    SCRIPT_UPDATE_ERROR: "SCRIPT_UPDATE_ERROR"

}
